#!/usr/bin/env bash

sudo nix-collect-garbage -d
nix-collect-garbage -d
# sudo /nix/var/nix/profiles/system/bin/switch-to-configuration switch
# sudo nix-env --delete-generations old --profile /nix/var/nix/profiles/system
