#!/usr/bin/env bash

set -e

SPACE=$1

[[ ! "$SPACE" = "user" ]] && sudo nixos-rebuild switch --flake .#
[[ ! "$SPACE" = "system" ]] && NIXPKGS_ALLOW_INSECURE=1 home-manager switch --impure --flake .#skill
